
CREATE TABLE IF NOT EXISTS SALESMAN(
    SALESMAN_ID TEXT PRIMARY KEY,
    NAME TEXT,
    CITY TEXT,
    COMISSION REAL
);

INSERT INTO SALESMAN (SALESMAN_ID, NAME, CITY, COMISSION) VALUES
    ('5001', 'JAMES HOOG', 'NEW YORK', 0.15),
    ('5002', 'NAIL KNITE', 'PARIS', 0.13),
    ('5005', 'PIT ALEX', 'LONDON', 0.11);


CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUSTOMER_ID TEXT PRIMARY KEY,
    CUST_NAME TEXT,
    CITY TEXT,
    GRADE INTEGER,
    SALESMAN_ID TEXT,
    FOREIGN KEY (SALESMAN_ID) REFERENCES SALESMAN(SALESMAN_ID)
);

INSERT INTO CUSTOMER (CUSTOMER_ID, CUST_NAME, CITY, GRADE, SALESMAN_ID) VALUES
    ('3002', 'NICK RIMANDO', 'NEW YORK', 100, '5001'),
    ('3007', 'BRAD DAVIS', 'NEW YORK', 200, '5001'),
    ('3005', 'GRAHM ZUSI', 'CALIFORNIA', 200, '5002');

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_NO TEXT PRIMARY KEY,
    PURCH_AMT REAL,
    ORD_DATE TEXT,
    CUSTOMER_ID TEXT,
    SALESMAN_ID TEXT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (SALESMAN_ID) REFERENCES SALESMAN(SALESMAN_ID)
);

INSERT INTO ORDERS (ORDER_NO, PURCH_AMT, ORD_DATE, CUSTOMER_ID, SALESMAN_ID) VALUES
    ('7001', 150.5, '2012-10-05', '3005', '5002'),
    ('7009', 270.65, '2012-09-10', '3005', '5001'),
    ('7002', 65.26, '2012-10-05', '3002', '5001'); 


SELECT C.CUST_NAME, S.NAME, S.CITY
FROM CUSTOMER C
JOIN SALESMAN S ON C.CITY = S.CITY;

SELECT C.CUST_NAME, S.NAME
FROM CUSTOMER C
JOIN SALESMAN S ON C.SALESMAN_ID = S.SALESMAN_ID;

SELECT O.ORDER_NO, C.CUST_NAME, O.CUSTOMER_ID, O.SALESMAN_ID
FROM ORDERS O
JOIN CUSTOMER C ON O.CUSTOMER_ID = C.CUSTOMER_ID
JOIN SALESMAN S ON O.SALESMAN_ID = S.SALESMAN_ID
WHERE C.CITY <> S.CITY;

SELECT O.ORDER_NO, C.CUST_NAME
FROM ORDERS O
JOIN CUSTOMER C ON O.CUSTOMER_ID = C.CUSTOMER_ID;

SELECT C.CUST_NAME AS "Customer", C.GRADE AS "Grade"
FROM ORDERS O
JOIN SALESMAN S ON O.SALESMAN_ID = S.SALESMAN_ID
JOIN CUSTOMER C ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.GRADE IS NOT NULL;

SELECT C.CUST_NAME AS "Customer",
       C.CITY AS "City",
       S.NAME AS "Salesman",
       S.COMISSION
FROM CUSTOMER C
JOIN SALESMAN S ON C.SALESMAN_ID = S.SALESMAN_ID
WHERE S.COMISSION BETWEEN 0.12 AND 0.14;

SELECT O.ORDER_NO, C.CUST_NAME, S.COMISSION AS "Commission%",
       O.PURCH_AMT * S.COMISSION AS "Commission"
FROM ORDERS O
JOIN SALESMAN S ON O.SALESMAN_ID = S.SALESMAN_ID
JOIN CUSTOMER C ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.GRADE >= 200;

SELECT *
FROM CUSTOMER C
JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.ORD_DATE = '2012-10-05';
